# Data collecting

## Working on csv downloaded data

In [1]:
import pandas as pd

df = pd.read_csv('C:/Users/progr/OneDrive/Documentos/Miguel/PROJETOS/Rainha_de_Saba/01_data/raw/EUR_USD_Historical_Data.csv')  
df

           Date   Price    Open    High     Low  Vol. Change %
0    04/16/2025  1.1399  1.1294  1.1413  1.1293   NaN    0.93%
1    04/15/2025  1.1294  1.1349  1.1379  1.1264   NaN   -0.48%
2    04/14/2025  1.1349  1.1313  1.1425  1.1282   NaN   -0.10%
3    04/11/2025  1.1360  1.1202  1.1475  1.1189   NaN    1.46%
4    04/10/2025  1.1197  1.0951  1.1242  1.0943   NaN    2.25%
..          ...     ...     ...     ...     ...   ...      ...
257  04/22/2024  1.0654  1.0656  1.0671  1.0623   NaN    0.00%
258  04/19/2024  1.0654  1.0645  1.0678  1.0610   NaN    0.10%
259  04/18/2024  1.0643  1.0672  1.0690  1.0641   NaN   -0.26%
260  04/17/2024  1.0671  1.0619  1.0680  1.0605   NaN    0.51%
261  04/16/2024  1.0617  1.0624  1.0654  1.0601   NaN   -0.05%

[262 rows x 7 columns]

In [2]:
dataframe = pd.DataFrame(df)
dataframe

           Date   Price    Open    High     Low  Vol. Change %
0    04/16/2025  1.1399  1.1294  1.1413  1.1293   NaN    0.93%
1    04/15/2025  1.1294  1.1349  1.1379  1.1264   NaN   -0.48%
2    04/14/2025  1.1349  1.1313  1.1425  1.1282   NaN   -0.10%
3    04/11/2025  1.1360  1.1202  1.1475  1.1189   NaN    1.46%
4    04/10/2025  1.1197  1.0951  1.1242  1.0943   NaN    2.25%
..          ...     ...     ...     ...     ...   ...      ...
257  04/22/2024  1.0654  1.0656  1.0671  1.0623   NaN    0.00%
258  04/19/2024  1.0654  1.0645  1.0678  1.0610   NaN    0.10%
259  04/18/2024  1.0643  1.0672  1.0690  1.0641   NaN   -0.26%
260  04/17/2024  1.0671  1.0619  1.0680  1.0605   NaN    0.51%
261  04/16/2024  1.0617  1.0624  1.0654  1.0601   NaN   -0.05%

[262 rows x 7 columns]

# Yahoo Finance

Mais informações sobre o funcionamento desta API: https://yfinance-python.org/

In [3]:
!pip install yfinance --upgrade

Requirement already satisfied: yfinance in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (0.2.55)
Requirement already satisfied: pandas>=1.3.0 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from yfinance) (2.2.1)
Requirement already satisfied: numpy>=1.16.5 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from yfinance) (1.26.3)
Requirement already satisfied: requests>=2.31 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from yfinance) (2.31.0)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from yfinance) (0.0.11)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from yfinance) (4.1.0)
Requirement already satisfied: pytz>=2022.5 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from yfinance) (2023.3.post1)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from yfinance) (2.4.1)
Requirement already satisfied: peewee>=3.16.2 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from yfinance) (3.17.1)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from yfinance) (4.12.2)
Requirement already satisfied: soupsieve>1.2 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from pandas>=1.3.0->yfinance) (2023.4)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from requests>=2.31->yfinance) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from requests>=2.31->yfinance) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from requests>=2.31->yfinance) (2023.11.17)
Requirement already satisfied: six>=1.5 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.16.0)

[notice] A new release of pip is available: 23.2.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd
import yfinance as yf
import datetime

In [5]:
tickers = yf.Tickers('MSFT AAPL GOOG')
tickers.tickers['MSFT'].info
#yf.download(['MSFT', 'AAPL', 'GOOG'], period='1mo')

TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'str'

In [6]:
df = yf.download("AAPL",
    start="2011-01-01",
    end="2021-12-31",
    progress=False)

1 Failed download:
['AAPL']: Exception('%ticker%: No price data found, symbol may be delisted (1d 2011-01-01 -> 2021-12-31)')

# Nasdaq Data Link

In [7]:
!pip3 install nasdaq-data-link

Requirement already satisfied: nasdaq-data-link in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (1.0.4)

[notice] A new release of pip is available: 23.2.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas>=0.14 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from nasdaq-data-link) (2.2.1)
Requirement already satisfied: numpy>=1.8 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from nasdaq-data-link) (1.26.3)
Requirement already satisfied: requests>=2.7.0 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from nasdaq-data-link) (2.31.0)
Requirement already satisfied: inflection>=0.3.1 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from nasdaq-data-link) (0.5.1)
Requirement already satisfied: python-dateutil in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from nasdaq-data-link) (2.8.2)
Requirement already satisfied: six in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from nasdaq-data-link) (1.16.0)
Requirement already satisfied: more-itertools in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from nasdaq-data-link) (10.6.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from pandas>=0.14->nasdaq-data-link) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from pandas>=0.14->nasdaq-data-link) (2023.4)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from requests>=2.7.0->nasdaq-data-link) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from requests>=2.7.0->nasdaq-data-link) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from requests>=2.7.0->nasdaq-data-link) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from requests>=2.7.0->nasdaq-data-link) (2023.11.17)

In [8]:
import pandas as pd
import nasdaqdatalink

nasdaqdatalink.ApiConfig.api_key = "EvCpuRsGgEqfzPV4nzwn"
data = nasdaqdatalink.get('NSE/OIL')
print(data.head())

ModuleNotFoundError: No module named 'nasdaqdatalink'

# Intrinio

Fazer a Intrinio funcionar é um pouco mais complexo. É necessário seguir um procediment envolendo a instalação de uma biblioteca para administração de web sockets, especificamente esta: https://pypi.org/project/websocket-client/

Você deve aind executar seus códigos Intrinio utilizando o SDK (Sofwtare Ddevelpment Kit) da Intirinio específico parar Python. Link: https://github.com/intrinio/intrinio-realtime-python-sdk?tab=readme-ov-file

In [10]:
!pip install intriniorealtime
!pip install websocket-client

Requirement already satisfied: intriniorealtime in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (5.4.3)
Requirement already satisfied: requests>=2.26.0 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from intriniorealtime) (2.31.0)
Requirement already satisfied: websocket-client>=1.2.1 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from intriniorealtime) (1.7.0)
Requirement already satisfied: wsaccel>=0.6.3 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from intriniorealtime) (0.6.7)
Requirement already satisfied: intrinio-sdk>=6.26.0 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from intriniorealtime) (6.35.0)
Requirement already satisfied: urllib3>=1.15 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from intrinio-sdk>=6.26.0->intriniorealtime) (2.1.0)
Requirement already satisfied: six>=1.10 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from intrinio-sdk>=6.26.0->intriniorealtime) (1.16.0)
Requirement already satisfied: certifi in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from intrinio-sdk>=6.26.0->intriniorealtime) (2023.11.17)
Requirement already satisfied: python-dateutil in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from intrinio-sdk>=6.26.0->intriniorealtime) (2.8.2)
Requirement already satisfied: retrying>=1.3.3 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from intrinio-sdk>=6.26.0->intriniorealtime) (1.3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from requests>=2.26.0->intriniorealtime) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from requests>=2.26.0->intriniorealtime) (3.6)

[notice] A new release of pip is available: 23.2.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: websocket-client in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (1.7.0)

[notice] A new release of pip is available: 23.2.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
# MINHA CHAVE API: "OmMwMDU4MzQwZWFjZTk3MjRjNTM3ZTQ5NTgwNDIyMGRl"

intrinio.ApiClient().set_api_key("OmMwMDU4MzQwZWFjZTk3MjRjNTM3ZTQ5NTgwNDIyMGRl")
security_api = intrinio.SecurityApi()

NameError: name 'intrinio' is not defined

Para executar a verificação da API Key disponibilizada pelo Intrinio, executamos o seguinte comando no prompt:

```
docker compose build
docker compose run client
```

In [11]:
!docker compose build
!docker compose run client

'docker' nao é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.
'docker' nao é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

In [8]:
from intriniorealtime.client import IntrinioRealtimeClient

def on_quote(quote, backlog):
    print("QUOTE: " , quote, "BACKLOG LENGTH: ", backlog)
    
options = {
    'api_key': 'YOUR_INTRINIO_API_KEY',
    'provider': 'iex',
    'on_quote': on_quote
}

client = IntrinioRealtimeClient(options)
client.join(['AAPL','GE','MSFT'])
client.connect()
client.keep_alive()

ModuleNotFoundError: No module named 'intriniorealtime'

# Alpha Vantage

In [17]:
!pip install alpha_vantage

Requirement already satisfied: alpha_vantage in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (3.0.0)
Requirement already satisfied: aiohttp in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from alpha_vantage) (3.11.16)
Requirement already satisfied: requests in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from alpha_vantage) (2.31.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from aiohttp->alpha_vantage) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from aiohttp->alpha_vantage) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from aiohttp->alpha_vantage) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from aiohttp->alpha_vantage) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from aiohttp->alpha_vantage) (6.4.3)
Requirement already satisfied: propcache>=0.2.0 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from aiohttp->alpha_vantage) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from aiohttp->alpha_vantage) (1.20.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from requests->alpha_vantage) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from requests->alpha_vantage) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from requests->alpha_vantage) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from requests->alpha_vantage) (2023.11.17)

[notice] A new release of pip is available: 23.2.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [19]:
from alpha_vantage.timeseries import TimeSeries

ModuleNotFoundError: No module named 'alpha_vantage'

In [20]:
ts = TimeSeries(key='8RDP03MYLD19D1II')
# Get json object with the intraday data and another with  the call's metadata
data, meta_data = ts.get_intraday('GOOGL')

NameError: name 'TimeSeries' is not defined

# CoinGecko

https://www.coingecko.com/

https://docs.coingecko.com/v3.0.1/reference/introduction

https://docs.coingecko.com/reference/introduction

Atenção: a CoinGecko é paga e cara!

In [23]:
!pip install -U pycoingecko

Requirement already satisfied: pycoingecko in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (3.2.0)

[notice] A new release of pip is available: 23.2.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: requests in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from pycoingecko) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from requests->pycoingecko) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from requests->pycoingecko) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from requests->pycoingecko) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\progr\.pyenv\pyenv-win\versions\3.12.0\lib\site-packages (from requests->pycoingecko) (2023.11.17)

In [21]:
from pycoingecko import CoinGeckoAPI
from datetime import datetime
import pandas as pd

ModuleNotFoundError: No module named 'pycoingecko'

### Vê-se que eu não estou muito bem servido de APIs para dados financeiros... Mas eu tenho que continuar tentado... 

Algumas simplesmente não parecem funcionar. Outras são muito complexas que demandarão um certo tempo para ser configuradas no meu projeto. Outras, como a CoinGecko, são pagas e bem caras.